[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[phases.setup.env]
NODE_ENV = "production"

[[phases.build.dependsOn]]
runtime = "nodejs"
version = "18"