[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[env]
NODE_ENV = "production"
NODE_VERSION = "18"