services:
  - type: web
    name: viet-co-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
  # Run schema push before starting the server so tables exist.
  # (Idempotent: drizzle-kit push only applies missing objects.)
  startCommand: npm run start
  preDeployCommand: npm run db:push && npm run seed:admin
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: viet-co-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: DEBUG_LOGS
        value: "false"
      - key: HOST
        value: 0.0.0.0
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_FORCE
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
  # Note: 'preDeployCommand' runs before each deploy but not on simple restarts.

databases:
  - name: viet-co-db
    plan: free
    region: oregon

# Optional documentation (ignored by YAML parser):
# After creating via Blueprint, set JWT_SECRET manually.
# Uncomment preDeployCommand once you switch from push to migrations.
