services:
  - type: web
    name: viet-co-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: viet-co-db
      - key: JWT_SECRET
        sync: false
      - key: DEBUG_LOGS
        value: "false"
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    autoDeploy: true
    # preDeployCommand: npm run migrate

databases:
  - name: viet-co-db
    plan: free
    region: oregon

# Optional documentation (ignored by YAML parser):
# After creating via Blueprint, set JWT_SECRET manually.
# Uncomment preDeployCommand once you switch from push to migrations.
